import type { Partner } from "@/types/partner";

export const ALL_PARTNERS: Partner[] = [
  // DKI Jakarta
  {
    id: 1,
    name: "Bengkel Maju Jaya Motor",
    owner: "Bpk. Ahmad Hidayat",
    email: "ahmad@majujayamotor.com",
    whatsapp: "081234567891",
    kategori: "Bengkel Umum",
    province: "DKI Jakarta",
    city: "Jakarta Selatan",
    address:
      "Jl. TB Simatupang No. 45, Cilandak, Jakarta Selatan, DKI Jakarta 12430",
    mapsLink: "https://maps.google.com/?q=-6.2615,106.8106",
    avatar:
      "https://ui-avatars.com/api/?name=MJ&background=1A2332&color=F5C800&bold=true&size=80",
    lat: -6.2615,
    lng: 106.8106,
  },
  {
    id: 2,
    name: "Toko Ban Mega Jaya",
    owner: "Ibu Sari Dewi Utami",
    email: "sari@megajayaban.co.id",
    whatsapp: "082111223344",
    kategori: "Toko Ban",
    province: "DKI Jakarta",
    city: "Jakarta Barat",
    address:
      "Jl. Daan Mogot Km. 15 No. 32, Cengkareng, Jakarta Barat, DKI Jakarta 11730",
    mapsLink: "https://maps.google.com/?q=-6.1683,106.7630",
    avatar:
      "https://ui-avatars.com/api/?name=TM&background=EA580C&color=fff&bold=true&size=80",
    lat: -6.1683,
    lng: 106.763,
  },
  {
    id: 3,
    name: "Pusat Aksesoris Otomotif IKM",
    owner: "Bpk. Rudi Hartono",
    email: "rudi@ikmaksesoris.com",
    whatsapp: "081398765432",
    kategori: "Aksesoris Mobil",
    province: "DKI Jakarta",
    city: "Jakarta Pusat",
    address:
      "Jl. Tanah Abang III No. 17, Tanah Abang, Jakarta Pusat, DKI Jakarta 10170",
    mapsLink: "https://maps.google.com/?q=-6.1751,106.8650",
    avatar:
      "https://ui-avatars.com/api/?name=IK&background=7C3AED&color=fff&bold=true&size=80",
    lat: -6.1751,
    lng: 106.865,
  },
  {
    id: 4,
    name: "Auto Detailing Prima",
    owner: "Bpk. Dodi Kusuma",
    email: "dodi@autodetailingprima.id",
    whatsapp: "085678901234",
    kategori: "Detailing & Cuci Mobil",
    province: "DKI Jakarta",
    city: "Jakarta Timur",
    address:
      "Jl. Raya Bekasi Km. 18 No. 5, Cakung, Jakarta Timur, DKI Jakarta 13910",
    mapsLink: "https://maps.google.com/?q=-6.2250,106.9000",
    avatar:
      "https://ui-avatars.com/api/?name=AP&background=0F766E&color=fff&bold=true&size=80",
    lat: -6.225,
    lng: 106.9,
  },
  // Jawa Barat
  {
    id: 5,
    name: "Bengkel Spesialis Toyota Bandung",
    owner: "Bpk. Agus Permadi",
    email: "agus@bengkeltoyotabandung.com",
    whatsapp: "082234567890",
    kategori: "Bengkel Spesialis",
    province: "Jawa Barat",
    city: "Bandung",
    address: "Jl. Pasteur No. 120, Sukajadi, Kota Bandung, Jawa Barat 40161",
    mapsLink: "https://maps.google.com/?q=-6.9175,107.6191",
    avatar:
      "https://ui-avatars.com/api/?name=BS&background=1D4ED8&color=fff&bold=true&size=80",
    lat: -6.9175,
    lng: 107.6191,
  },
  {
    id: 6,
    name: "Oli & Spare Part Bekasi Jaya",
    owner: "Ibu Lestari Wulandari",
    email: "lestari@olibekasiajaya.com",
    whatsapp: "081122334455",
    kategori: "Oli & Spare Part",
    province: "Jawa Barat",
    city: "Bekasi",
    address:
      "Jl. Ahmad Yani No. 77, Bekasi Timur, Kota Bekasi, Jawa Barat 17111",
    mapsLink: "https://maps.google.com/?q=-6.2383,106.9756",
    avatar:
      "https://ui-avatars.com/api/?name=OB&background=CA8A04&color=fff&bold=true&size=80",
    lat: -6.2383,
    lng: 106.9756,
  },
  {
    id: 7,
    name: "Bengkel Umum Bogor Mandiri",
    owner: "Bpk. Hendra Saputra",
    email: "hendra@bengkelbogor.co.id",
    whatsapp: "089876543210",
    kategori: "Bengkel Umum",
    province: "Jawa Barat",
    city: "Bogor",
    address:
      "Jl. Pajajaran No. 55A, Bogor Tengah, Kota Bogor, Jawa Barat 16128",
    mapsLink: "https://maps.google.com/?q=-6.5971,106.8060",
    avatar:
      "https://ui-avatars.com/api/?name=BM&background=166534&color=fff&bold=true&size=80",
    lat: -6.5971,
    lng: 106.806,
  },
  // Jawa Timur
  {
    id: 8,
    name: "Modifikasi & Accessories Surabaya",
    owner: "Bpk. Bambang Wibowo",
    email: "bambang@modifsub.id",
    whatsapp: "081345678901",
    kategori: "Modifikasi Mobil",
    province: "Jawa Timur",
    city: "Surabaya",
    address: "Jl. Raya Darmo No. 100, Wonokromo, Surabaya, Jawa Timur 60241",
    mapsLink: "https://maps.google.com/?q=-7.2575,112.7521",
    avatar:
      "https://ui-avatars.com/api/?name=MS&background=9F1239&color=fff&bold=true&size=80",
    lat: -7.2575,
    lng: 112.7521,
  },
  {
    id: 9,
    name: "Toko Ban Malang Sejahtera",
    owner: "Ibu Endah Puspitasari",
    email: "endah@banmalang.com",
    whatsapp: "087654321098",
    kategori: "Toko Ban",
    province: "Jawa Timur",
    city: "Malang",
    address: "Jl. Kawi No. 24, Klojen, Kota Malang, Jawa Timur 65119",
    mapsLink: "https://maps.google.com/?q=-7.9797,112.6304",
    avatar:
      "https://ui-avatars.com/api/?name=TM&background=EA580C&color=fff&bold=true&size=80",
    lat: -7.9797,
    lng: 112.6304,
  },
  {
    id: 10,
    name: "Sidoarjo Auto Care",
    owner: "Bpk. Teguh Santoso",
    email: "teguh@sidoarjoautocare.com",
    whatsapp: "082298765432",
    kategori: "Detailing & Cuci Mobil",
    province: "Jawa Timur",
    city: "Sidoarjo",
    address: "Jl. Ahmad Yani No. 15, Sidoarjo, Jawa Timur 61218",
    mapsLink: "https://maps.google.com/?q=-7.4460,112.7185",
    avatar:
      "https://ui-avatars.com/api/?name=SA&background=0F766E&color=fff&bold=true&size=80",
    lat: -7.446,
    lng: 112.7185,
  },
  // Bali
  {
    id: 11,
    name: "Bengkel Bali Otomotif",
    owner: "Bpk. I Wayan Surya",
    email: "wayan@bengkalbali.com",
    whatsapp: "081234567890",
    kategori: "Bengkel Umum",
    province: "Bali",
    city: "Denpasar",
    address:
      "Jl. Bypass Ngurah Rai No. 88, Sanur, Denpasar Selatan, Bali 80228",
    mapsLink: "https://maps.google.com/?q=-8.6705,115.2126",
    avatar:
      "https://ui-avatars.com/api/?name=BO&background=1A2332&color=F5C800&bold=true&size=80",
    lat: -8.6705,
    lng: 115.2126,
  },
  {
    id: 12,
    name: "Kuta Aksesoris & Spare Part",
    owner: "Ibu Ni Made Ayu",
    email: "nimade@kutaaksesoris.com",
    whatsapp: "087711223344",
    kategori: "Aksesoris Mobil",
    province: "Bali",
    city: "Badung",
    address: "Jl. Raya Kuta No. 200, Kuta, Badung, Bali 80361",
    mapsLink: "https://maps.google.com/?q=-8.5069,115.2625",
    avatar:
      "https://ui-avatars.com/api/?name=KA&background=7C3AED&color=fff&bold=true&size=80",
    lat: -8.5069,
    lng: 115.2625,
  },
  {
    id: 13,
    name: "Gianyar Ban & Oli",
    owner: "Bpk. I Ketut Dharma",
    email: "ketut@gianyarbanoli.id",
    whatsapp: "081556677889",
    kategori: "Oli & Spare Part",
    province: "Bali",
    city: "Gianyar",
    address: "Jl. Astina Utara No. 5, Gianyar, Bali 80511",
    mapsLink: "https://maps.google.com/?q=-8.5400,115.3307",
    avatar:
      "https://ui-avatars.com/api/?name=GB&background=CA8A04&color=fff&bold=true&size=80",
    lat: -8.54,
    lng: 115.3307,
  },
  // Jawa Tengah
  {
    id: 14,
    name: "Bengkel Spesialis Honda Semarang",
    owner: "Bpk. Slamet Riyadi",
    email: "slamet@bengkelhonda-smg.com",
    whatsapp: "082244556677",
    kategori: "Bengkel Spesialis",
    province: "Jawa Tengah",
    city: "Semarang",
    address:
      "Jl. Pandanaran No. 78, Pleburan, Semarang Selatan, Jawa Tengah 50241",
    mapsLink: "https://maps.google.com/?q=-6.9932,110.4203",
    avatar:
      "https://ui-avatars.com/api/?name=BH&background=1D4ED8&color=fff&bold=true&size=80",
    lat: -6.9932,
    lng: 110.4203,
  },
  {
    id: 15,
    name: "Solo Modif Center",
    owner: "Bpk. Joko Purnomo",
    email: "joko@solomodif.co.id",
    whatsapp: "085512345678",
    kategori: "Modifikasi Mobil",
    province: "Jawa Tengah",
    city: "Surakarta",
    address: "Jl. Slamet Riyadi No. 300, Laweyan, Surakarta, Jawa Tengah 57141",
    mapsLink: "https://maps.google.com/?q=-7.5755,110.8243",
    avatar:
      "https://ui-avatars.com/api/?name=SC&background=9F1239&color=fff&bold=true&size=80",
    lat: -7.5755,
    lng: 110.8243,
  },
  // Sumatera Utara
  {
    id: 16,
    name: "Medan Prima Bengkel",
    owner: "Bpk. Harun Al Rasyid",
    email: "harun@medanprimabengkel.com",
    whatsapp: "081365432109",
    kategori: "Bengkel Umum",
    province: "Sumatera Utara",
    city: "Medan",
    address:
      "Jl. Asia No. 123, Kota Matsum IV, Medan Area, Kota Medan, Sumut 20214",
    mapsLink: "https://maps.google.com/?q=3.5952,98.6722",
    avatar:
      "https://ui-avatars.com/api/?name=MP&background=1A2332&color=F5C800&bold=true&size=80",
    lat: 3.5952,
    lng: 98.6722,
  },
  {
    id: 17,
    name: "Toko Ban Deli Makmur",
    owner: "Ibu Fatimah Nasution",
    email: "fatimah@bandelimakmur.id",
    whatsapp: "082199887766",
    kategori: "Toko Ban",
    province: "Sumatera Utara",
    city: "Deli Serdang",
    address:
      "Jl. Thamrin No. 44, Lubuk Pakam, Deli Serdang, Sumatera Utara 20514",
    mapsLink: "https://maps.google.com/?q=3.4731,98.8392",
    avatar:
      "https://ui-avatars.com/api/?name=TD&background=EA580C&color=fff&bold=true&size=80",
    lat: 3.4731,
    lng: 98.8392,
  },
  // Sulawesi Selatan
  {
    id: 18,
    name: "Makassar Auto Detailing",
    owner: "Bpk. Syahrul Ramadhan",
    email: "syahrul@makassardetailing.com",
    whatsapp: "081411223344",
    kategori: "Detailing & Cuci Mobil",
    province: "Sulawesi Selatan",
    city: "Makassar",
    address:
      "Jl. Urip Sumoharjo No. 55, Panakkukang, Makassar, Sulawesi Selatan 90231",
    mapsLink: "https://maps.google.com/?q=-5.1477,119.4327",
    avatar:
      "https://ui-avatars.com/api/?name=MA&background=0F766E&color=fff&bold=true&size=80",
    lat: -5.1477,
    lng: 119.4327,
  },
  {
    id: 19,
    name: "Gowa Spare Part & Aksesoris",
    owner: "Ibu Andi Risna Wahyuni",
    email: "andi.risna@gowaaksesoris.id",
    whatsapp: "085588990011",
    kategori: "Aksesoris Mobil",
    province: "Sulawesi Selatan",
    city: "Gowa",
    address:
      "Jl. Sultan Hasanuddin No. 12, Somba Opu, Gowa, Sulawesi Selatan 92111",
    mapsLink: "https://maps.google.com/?q=-5.2200,119.4800",
    avatar:
      "https://ui-avatars.com/api/?name=GS&background=7C3AED&color=fff&bold=true&size=80",
    lat: -5.22,
    lng: 119.48,
  },
  // Kalimantan Timur
  {
    id: 20,
    name: "Balikpapan Bengkel Spesialis",
    owner: "Bpk. Eko Prasetyo",
    email: "eko@bengkelbalikpapan.com",
    whatsapp: "081453216789",
    kategori: "Bengkel Spesialis",
    province: "Kalimantan Timur",
    city: "Balikpapan",
    address:
      "Jl. Jenderal Sudirman No. 88, Balikpapan Kota, Kalimantan Timur 76112",
    mapsLink: "https://maps.google.com/?q=-1.2675,116.8289",
    avatar:
      "https://ui-avatars.com/api/?name=BB&background=1D4ED8&color=fff&bold=true&size=80",
    lat: -1.2675,
    lng: 116.8289,
  },
  {
    id: 21,
    name: "Samarinda Oli & Pelumas",
    owner: "Ibu Yuni Ariani",
    email: "yuni@samarindaoli.co.id",
    whatsapp: "082277889900",
    kategori: "Oli & Spare Part",
    province: "Kalimantan Timur",
    city: "Samarinda",
    address:
      "Jl. Untung Suropati No. 35, Samarinda Ilir, Samarinda, Kalimantan Timur 75117",
    mapsLink: "https://maps.google.com/?q=-0.5022,117.1536",
    avatar:
      "https://ui-avatars.com/api/?name=SO&background=CA8A04&color=fff&bold=true&size=80",
    lat: -0.5022,
    lng: 117.1536,
  },
  // Riau
  {
    id: 22,
    name: "Pekanbaru Car Wash & Detailing",
    owner: "Bpk. Mustafa Kamal",
    email: "mustafa@pkucarwash.com",
    whatsapp: "081372345678",
    kategori: "Detailing & Cuci Mobil",
    province: "Riau",
    city: "Pekanbaru",
    address: "Jl. Sudirman No. 170, Tampan, Pekanbaru, Riau 28291",
    mapsLink: "https://maps.google.com/?q=0.5070,101.4478",
    avatar:
      "https://ui-avatars.com/api/?name=PC&background=0F766E&color=fff&bold=true&size=80",
    lat: 0.507,
    lng: 101.4478,
  },
  // DIY Yogyakarta
  {
    id: 23,
    name: "Jogja Modifikasi & Custom",
    owner: "Bpk. Wahyu Widodo",
    email: "wahyu@jogjacustom.id",
    whatsapp: "082345678901",
    kategori: "Modifikasi Mobil",
    province: "DIY Yogyakarta",
    city: "Yogyakarta",
    address: "Jl. Mangkubumi No. 33, Gedongtengen, Kota Yogyakarta, DIY 55271",
    mapsLink: "https://maps.google.com/?q=-7.7956,110.3695",
    avatar:
      "https://ui-avatars.com/api/?name=JM&background=9F1239&color=fff&bold=true&size=80",
    lat: -7.7956,
    lng: 110.3695,
  },
];
